
version: '3.8'

services:
  live-location-app:
    build: . 
    ports:
      - "7000:7000" 
    environment:
      DB_USER: postgres    
      DB_HOST:  
      DB_NAME: your_db_name_here    
      DB_PASSWORD: your_db_password_here 
      DB_PORT: 5432 
    networks:
      - app-network
    restart: unless-stopped 
networks:
  app-network:
    driver: bridge